<img src="https://docs.google.com/uc?export=download&id=1lAgBWrlSFP0A4sLSIatnKd6iv0bFOEov">

# Data manipulation: Numpy

# 1-Numpy ndarrays

* **Numpy** for Numerical Python, a library for** numerical computing** in Python.

* It defines:

  * **ndarray** : multidimentioanl **array **

  * Fast** Mathematical functions **and** operations** with ndarray

  * Tools for** reading/writing ** **array** data from/to disk

  * **Linear algebra**, r**andom number generation**, and **Fourrier transform** capabilities

  * A** C API** for connecting NumPy with libraries written in **C**,** C++**, or **FORTRAN**.

* We will focus int this course on the **4** first points.

* **ndarray** is a **multidimensional** array object = a generic multidimensional **container** for data of the same type.

In [1]:
a= [1,2,3]
# a is a list
a


[1, 2, 3]

In [2]:
# import numpy to use ndarray
import numpy as np

#creating an ndarray by transforming a list using array function
b = np.array(a)

# b is an ndarray
b

array([1, 2, 3])

* an **ndarray** is charecterised by its **shape** and **dimension**



In [3]:
#create an ndarray from a list of two same sized list
c= np.array([[1,2,3],[4,5,6]])
print(c)

#create a 3 dimension ndarray
d= np.array([[[5,0,1],[9,7,-1],[2,3,5]],[[11,21,33],[22,5,16],[7,8,9]]])


#the  ndim (dimension) and shape attributes
print("d.dimension=",d.ndim)
print("d.shape =",d.shape)

[[1 2 3]
 [4 5 6]]
d.dimension= 3
d.shape = (2, 3, 3)


In [4]:
# asarray function : create an ndarray from the input. 
# if the input is an ndarray, it will not be copied:
# the output and the input will refer to the same element.
g = np.asarray(b)
g[0]=155
print ("g=",g)
print("b=",b)
       
'''
array function : create an ndarray from the input. 
even if the input is an ndarray, it will by default be copied:
the output and the input will refer to different elements.
To behave like asarray, it must be called with the optional argument 'copy'
set to false: copy(b,copy=False)
'''

h = np.array(b)
h[1]= 156
print("h=",h)
print("b=",b)


g= [155   2   3]
b= [155   2   3]
h= [155 156   3]
b= [155   2   3]


In [5]:
# function eye (or identity), returns the identity matrix
id1 = np.eye(3)
print (id1)
# arrange return a range in an ndarray format
ar = np.arange(1,9,3)
print (ar)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 4 7]


* each of the following functions has two versions: **function-name** and **function-nam_like**

In [6]:
# 2 x 2 ndarray of ones
on = np.ones((2,2))
print ("on=",on)
# ndarray with the same shape and type as "c"
on_l = np.ones_like(c)
print ("on_l=",on_l)

on= [[1. 1.]
 [1. 1.]]
on_l= [[1 1 1]
 [1 1 1]]


In [7]:
# ndarray full with zeros
f = np.zeros(2)
print("f=",f)
# ndarray "empty"= no default values (random)
k = np.empty(6)
print("k=",k)
# ndarray full with the given value
y = np.full((2,4),0.5)
print("y=",y)

f= [0. 0.]
k= [2.16951735e-316 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000]
y= [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


* The ndarray can be created specifying a type "**dtype**"
* The types can be:

  * int : signed (i1, i2, i4 or i8) and unsigned (u1, u2, u4 or u8)
  * float:  f2, f4 or f, f8 or d, f16 or g
  * complex: c8, c16, c32
  * boolean: ?
  * object: O
  * String: S  . Fixed length ASCII String type, (S"number" for a stirng of "number" byte size)
  * Unicode: U . Fixed length Unicode type, (U"number" for unicode of "number" of certain_byte size )

In [8]:
a = np.full (5,3.2,dtype="i8")
print(a)

[3 3 3 3 3]


#2- Indexing

* **ndarray**  can be** inexed** by: integers, arrays, slices,and Boolean

In [9]:
c[0]

array([1, 2, 3])

In [10]:
ind = np.ones(2,dtype="i4")
c[ind]

array([[4, 5, 6],
       [4, 5, 6]])

In [11]:
c[ : , 0:2]

array([[1, 2],
       [4, 5]])

In [12]:
ind2 = np.full_like(c,False, dtype="?")
print("ind2=",ind2)
ind2[0]=True
print("ind2=",ind2)
ind2[1,0]=True
print("ind2=",ind2)
c[ind2]

ind2= [[False False False]
 [False False False]]
ind2= [[ True  True  True]
 [False False False]]
ind2= [[ True  True  True]
 [ True False False]]


array([1, 2, 3, 4])

* Using **slices** to create arrays from **other** ndarrays **doesn't** create  **copies**
* To have **distinct** arrays, we have to use the **method copy**


In [13]:
 # creating part ndarray from a slice of c ndarray
part = c[:2,0:2]
print("part=\n",part)
part[0,1]=1000
# modification of cell(0,1) of part will 
# alter c values too.
print("now part = \n",part)
print("and c now =\n",c)

part=
 [[1 2]
 [4 5]]
now part = 
 [[   1 1000]
 [   4    5]]
and c now =
 [[   1 1000    3]
 [   4    5    6]]


In [14]:
c = np.array([[1,2,3],[4,5,6]])
 # part2 is a slice copy of c
part2 = c[:2,0:2].copy()
print("part2=\n",part2)
part2[0,1]=1000
# modification of cell(0,1) of part2
# will not alter c values.
print("now part2 = \n",part)
print("and c always =\n",c)

part2=
 [[1 2]
 [4 5]]
now part2 = 
 [[   1 1000]
 [   4    5]]
and c always =
 [[1 2 3]
 [4 5 6]]


# 3- Operations with ndarray

## Artithmetic Operations and Linear Algebra

In [15]:
# element wise multiplication: cell by corresponding cell,
# matrices with the same shape
res = c * np.eye(3)[0:2,0:3]

# the result is a matrix with the same shape
print ("res=",res)

# matrix multiplication:  line by columuns
# different shapes but:
# number of columus of the first matrix == number of lines of the second matrix
res = c @ np.eye(3)  # same as np.dot(c,np.eye(3)) or c.dot(np.eye(3))

# the result is a matrix wiht:
# number of lines == number of lines of the first matrix
# number of columns == number of columnus of the first matrix
print("res=",res)


res= [[1. 0. 0.]
 [0. 5. 0.]]
res= [[1. 2. 3.]
 [4. 5. 6.]]


## Element wise multiplication vs Matrix multiplication

* To perform an **element wise multiplication**, the matrices mus have the **same shape**:

>$c_{2,3} =
 \begin{pmatrix}        
  1 & 2 & 3 \\
 5 & 6 & 7 
 \end{pmatrix}$
 ,  $d_{2,3} =
 \begin{pmatrix}
  1 & -1 &  0\\
 -5 &  1 &  2
 \end{pmatrix}$
 
 
 * **d** has to be **reshaped** to apply **matrix multiplication** with **c**
 
 * The reshape method called from **d** will not alter **d**, but It will create another reference (a view of) to **d**
 
 * After calling reshape with the follwing instruction:
 

```
d=d.reshape(3,2)
```
 **d** will be equal to:      $d_{3,2} =
 \begin{pmatrix}
  1 & -1\\
 0 & -5 \\
 1 & 2
 \end{pmatrix}$
 
 
 

 
 

In [16]:
# c * d
d = np.array([[1,-1,0],[-5,1,2]])
res = c * d
print ("res=\n",res)
# c @ d
# reshape method transform the shape of the array
# the number of scalar values remain the same
d=d.reshape(3,2)
print("new d=\n",d)
res = c.dot(d)
print("res2=\n",res)

res=
 [[  1  -2   0]
 [-20   5  12]]
new d=
 [[ 1 -1]
 [ 0 -5]
 [ 1  2]]
res2=
 [[  4  -5]
 [ 10 -17]]


## Arithmetic and logical Operations

In [17]:
# element wise addition same as matrix addition
res = c + d.reshape(c.shape)
print("res=",res)
# a different kind of addition
# 5 will be added to all values of c
res2 = c + 5
print("res2=",res2)
# inverse of values of an ndarray
res3 = 1 / c
print("res3=",res3)

res= [[ 2  1  3]
 [-1  6  8]]
res2= [[ 6  7  8]
 [ 9 10 11]]
res3= [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [18]:
#comparison
res = c > 3
print("res=",res)
# logical and: any value different from 0 is a True 
res2 = np.logical_and(c , np.array([[1,0,1],[0,0,1]]))
print("res2=",res2)


res= [[False False False]
 [ True  True  True]]
res2= [[ True False  True]
 [False False  True]]


* We can use logical operations to select certain elements of an array

In [19]:
# selecting elements greater than 2
c [c>2]

array([3, 4, 5, 6])

## Linear Algebra

* We already seen the matrix multiplication using **dot** **method**
or **np.dot function** or the operator **@**

* There are other functions related to linear Algebra as: **diag**,**trace**,
**inv**, **solve**, … etc.

* as for sacalrs, matrices have inverse regarding the matrix multiplication operation:
  
  >$mat * mat^{-1}= I$
  
  $I$  is the Identity matrix
  
* A system of linear equations can be represented by matrices:

  >$ mat * x = y $
  
  so: 
  
  >$ x=  mat^{-1} * y$
  
  
 * for example: 

  >$   x_{1} +  x_{2} = 4 $
  
  >$   x_{1} -  x_{2} = 0 $
  
  
  * in this case: 
  >$mat_{(2,2)} =
 \begin{pmatrix}        
  1 & 1  \\
 1 & -1 
 \end{pmatrix}$
 ,  $x_{(2,1)} =
 \begin{pmatrix}
  x_{1} \\
 x_{2}
 \end{pmatrix}$
 
 >   $y_{(2,1)} =
 \begin{pmatrix}
  4\\
 0
 \end{pmatrix}$
  
  and solution will be:
  
 $x_{(2,1)} =
 \begin{pmatrix}
  2 \\
 2
 \end{pmatrix}$

    

  


In [20]:
# diag returns the diagonal of a square matrix
mat = np.random.randn(3,3)
print ("mat==",mat)
print("mat diagonal ==", np.diag(mat))
# trace retruns the sum of the diagonal elements
print(np.trace(np.eye(4)))
# inv return the inverse of a square matrix : mat * inv(mat)== identity matrix
print("mat inverse==",np.linalg.inv(mat))
# solve return the solution of the equation Ax=B (the values of x)
print("solution of mat * x = I is: ",np.linalg.solve(mat,np.eye(3,3)))

mat== [[ 0.17118026 -1.04359942  0.16511674]
 [ 1.06032689  1.03158387  0.50774212]
 [-2.52429346  0.43223766  0.37344916]]
mat diagonal == [0.17118026 1.03158387 0.37344916]
4.0
mat inverse== [[ 0.07255619  0.20180938 -0.30646037]
 [-0.73426257  0.21040048  0.03858586]
 [ 1.34028697  1.12058921  0.56159142]]
solution of mat * x = I is:  [[ 0.07255619  0.20180938 -0.30646037]
 [-0.73426257  0.21040048  0.03858586]
 [ 1.34028697  1.12058921  0.56159142]]


## Some functions and methods

* Numpy defines a list of **element wise functions** applicable to :
  * One arrays as: **sqrt**, **exp**, **modf**,** log**, **sign**, **ceil** and** floor**, **cos**, **logical_not**, ... etc
  * Two arrays as **add**, **mod**, **maximum**... etc

In [21]:
# the fractional and integer parts of values of an ndarray
# it returns 2 ndarray
print("fractional part of c/2=",np.modf(c/2)[0])
print("integer part of c/2=",np.modf(c/2)[1])
# the sign function returns the signs of the ndarray elements: 1 , 0 or -1
print("signs of d=",np.sign(d))
# maximum between the elements of two ndarrays
print("maximum values are:",np.maximum(-c,d.reshape(c.shape)))

fractional part of c/2= [[0.5 0.  0.5]
 [0.  0.5 0. ]]
integer part of c/2= [[0. 1. 1.]
 [2. 2. 3.]]
signs of d= [[ 1 -1]
 [ 0 -1]
 [ 1  1]]
maximum values are: [[ 1 -1  0]
 [-4  1  2]]


*  There is a list of functions that permit the generation of ndarrays with certain values. For example: **randn**, **meshgrid**, and **where**

In [22]:
val = np.arange (0, 5, 1)
# the two arrays can be used to generate functions values
x, y= np.meshgrid(val, val)
print("x=",x)
print ("y=",y)
# function randn(2,3) will generate a (2x3) ndarray with random values
val = np.random.randn(2,3)
print("generated random values=",val)
# with "where" function we can generate ndarray values using conditional
res= np.where (c>3, "G","L")
print("res=",res)


x= [[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
y= [[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
generated random values= [[-1.58484867 -0.5152816   2.44731032]
 [ 1.05302372 -0.45778421  0.29859743]]
res= [['L' 'L' 'L']
 ['G' 'G' 'G']]


*  With the function **append** we can create a **new** ndarray by  appending  **new** values

In [39]:
print("c==",c)
# creating new array by appending a new values as a column (axis=1)
cn=np.append(c,[[7],[8]],axis= 1)
# creating new array by appending a new values as a row (axis=0)
cn2=np.append(c,[[7,8,9]],axis= 0)
print("c still ==",c)
print("first new ndarray=",cn)
print("second new ndarray=",cn2)


c== [[1 2 3]
 [4 5 6]]
c still == [[1 2 3]
 [4 5 6]]
first new ndarray= [[1 2 3 7]
 [4 5 6 8]]
second new ndarray= [[1 2 3]
 [4 5 6]
 [7 8 9]]


* ndarray objects define a list of useful methods like:  **mean**, **sum**, **cumsum**, **max**, **sort**,**T**,...etc

In [23]:
print("c==",c)
print ("maximum element of c==",c.max())
print ("the sum of elements of c ==",c.sum())
print ("the cumulative sum of elements of c ==", c.cumsum())
print("the mean of values of c ==",c.mean())


c== [[1 2 3]
 [4 5 6]]
maximum element of c== 6
the sum of elements of c == 21
the cumulative sum of elements of c == [ 1  3  6 10 15 21]
the mean of values of c == 3.5


In [24]:
# the T method: retruns the transpose of a matrix
# the lines become columns and vise versa
print("c==",c)
print ("c.T==",c.T)

c== [[1 2 3]
 [4 5 6]]
c.T== [[1 4]
 [2 5]
 [3 6]]


# 4- File loading and Saving

* It is possible to **save** and **load**  ndarrays into **binray format**

In [26]:
# save c to "file_c.npy"
np.save("file_c",c)
# loading c from "file_c.npy" into c2
c2= np.load("file_c.npy")
print("c2==",c2)
# saving multiple ndarrays: c and d into "files.npz"
np.savez("files",c=c,d=d)
#loading c and d from "files.npz"
res = np.load("files.npz")
print("c==",res["c"])
print("d==",res["d"])

c2== [[1 2 3]
 [4 5 6]]
c== [[1 2 3]
 [4 5 6]]
d== [[ 1 -1]
 [ 0 -5]
 [ 1  2]]


# 5- Structures with dtype

* **dtype constructor** can be used to create **structured** type.

In [27]:
myType = np.dtype([("code","U5"),("Value","i4")])
myAr = np.array([("A",10),("B",2),("C",15)],myType)
print("myAr==",myAr)
print("first element==",myAr[0])
print ("Codes in myAr==",myAr["code"])
print("second element value==",myAr[1]["Value"])

myAr== [('A', 10) ('B',  2) ('C', 15)]
first element== ('A', 10)
Codes in myAr== ['A' 'B' 'C']
second element value== 2


# References

* Wes McKinney. Python for data analysis: Data wrangling with Pandas, NumPy, and IPython. O’Reilly Media, Inc, 2018.

* SciPy.org. Data type objects. On-line at https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html. Accessed on 05-10-2018.